export const keyToString = (key: string): string => {
    const keyMap: { [key: string]: string } = {
        address: '주소',
        tel: '문의 및 안내',
        credit_card: '신용카드사용여부',
        parking: '주차시설',
        open_time: '영업시간',
        pets_available: '애완동물가능여부',
        baby_equipment_rental: '유모차 대여',
        closed_for_the_day: '휴일',
        play_area_for_children: '어린이놀이방여부',
        best_menu: '대표메뉴',
        rest_date: '쉬는날',
        time_available: '이용시간',
        sale_items: '판매품목',
        take_out: '포장가능여부',
        fair_day: '장서는날',
        smoking_section_available: '금연/흡연',
        reservation: '예약안내',
        fee: '입장료',
        occupancy: '수용가능인원',
        age_limit: '체험가능연령',
        scale: '시설 규모',
        start_date: '이벤트 시작일',
        end_date: '종료일',
        show_time: '공연시간',
        parking_fee: '주차요금',
        travel_time: '관람소요시간',
        discount: '할인정보',
        age_available: '관람가능연령',
        seasons: '이용시기',
        time_required: '관람소요시간',
        program: '행사프로그램',
    }

    return keyMap[key] || key
}