export { ReactComponent as KakaoButtonIcon } from './kakaoButton.svg'
export { ReactComponent as GoogleLogo } from './googleLogo.svg'
export { ReactComponent as DefaultProfile } from './defaultProfile.svg'
export { ReactComponent as TravelImage } from './travelImage.svg'
export { ReactComponent as LikeLocationImage } from './likeLocation.svg'
